### PR TITLE
filters out tweets where username does not match screen_name

### LINKED ISSUE #16: wrong posts in timelines?
I'm getting some wrong posts in timelines since I switched onto this server earlier today.  They're not just wrong posts; all the wrong posts have been ads.  So I suspect this may be happening on the Twitter end as a side-effect of the past several days' nonsense, but can anyone else confirm having seen anything like this?

I've deleted around 10 so far (out of around 500 tweets processed).

So, I'm guessing that the API endpoint the server is using is having sponsored tweets inserted into the timeline?

I may be able to add a check for this to the server; I'll give it a try, at least.

### PR DESCRIPTION
**Pull request by us3r1d**
Fixes #16 

this only inserts tweets in rss if the request's username matches the tweet's tweet.core.user_results.result.legacy.screen_name

I'm running this patch on my server (<https://twitter.oksocial.net/main/public>) now; I haven't gotten any wrongly-timelined tweets yet.

### CODE REVIEW

**Review by 12joan — CHANGES_REQUESTED** [review]
Thanks for the PR! Can you move this check to a new `.filter` in `twitter.ts` and explain in a brief comment why it's needed?

**Comment by us3r1d** [comment]
I'll give it a shot, but I don't really understand the syntax there.  (I have done almost no significant JS since GreaseMonkey was common. :-)

I'm guessing it would be something like:

`
.filter((tweet: any) => tweet.core.user_results.result.legacy.screen_name === username)
`

(assuming that has to be added after the current '=> tweet' line).

I'll leave my server running with the changed code overnight to see if any incorrect tweets make it through and update the PR in the morning if it looks good.

File: src/twitter.ts [hunk 1]
```diff
@@ -169,6 +169,9 @@ export const fetchTweets = async (redis: RedisClient, username: string): Promise
             .flatMap((instruction: any) => instruction.entries)
             .map((entry: any) => entry?.content?.itemContent?.tweet_results?.result)
             .filter((tweet: any) => tweet)
+            //only accept tweets whose screen_name actually matches :username
+            //  it may be a bug or it may be advertising, but incorrect tweets have been showing up on this API endpoint
```
Comment (12joan) [inline src/twitter.ts:173]:
```suggestion
            /**
             * Only accept Tweets whose screen_name matches username. It may be
             * a bug or it may be advertising, but incorrect Tweets have been
             * showing up on this API endpoint.
             */
```

**Review by 12joan — CHANGES_REQUESTED** [review]
Thanks! Let us know how it goes after testing.

**Review by 12joan — APPROVED** [review]

**Comment by us3r1d** [comment]
64 tweets overnight with no incorrect ones (only 2 of the accounts this follows are European :-)

I think it works, then.

**Comment by 12joan** [comment]
Nice! Thanks for all your hard work
